packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.15.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.0
  zod: ^3.23.8
  next: 15.0.4-canary.47
  next-auth: 5.0.0-beta.25
  react: 19.0.0
  react-dom: 19.0.0
  stripe: ^17.3.1
  vitest: 2.1.5
  "@types/react": 19.0.10
  "@types/react-dom": 19.0.1
  "@types/node": ^20.11.30
  "@t3-oss/env-nextjs": ^0.10.1
